### ISSUE TITLE
User isn't told if they can submit github issues in app

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#121]
As a user-person I can't see if there's a place where folks who are GitHub savvy could go to file issues on the app.  Are people not wanting that venue to be broadcast or is that just an omission?  I can totally see it either way. ;)

**Comment by sitapriyamoorthi** [comment]
@vortexing we had discussed this in one of the meetings. The idea being discussed that there should be a central repository for all issues that can be then distributed into the appropriate repos by one of us. Since currently we have different repos for different parts of PROOF. But I agree there should be some link to a repo to report issues and not an email to which to report troubles.

**Comment by sckott** [comment]
I'm almost positive the decision was made not to link to github issues, though i'm not sure what the thought process was - i think folks wanted users to send an email instead, which we have. 

I'd be up for adding link to issues

**Comment by sitapriyamoorthi** [comment]
So back in June ( I believe you were still on paternity at that time) there was this discussion : https://www.notion.so/fhdasl/June-Tech-Team-Innovation-c0ad405e322a46a396acd811a3814ea8?pvs=4#816f69309ebf44d0a97052f4906ffcf0

**Comment by sckott** [comment]
Thanks @sitapriyamoorthi That make sense to have a link that opens a new issue in https://github.com/getwilds/proof And then we can even transfer the issues to the respective repos. 

Should I go ahead and do this? @vortexing ?

**Comment by vortexing** [comment]
I think if that feels right to the the folks who would then be triaging those issues on the central proof repo, then do it.  If no one wants to be on point for that, just let it be how it is today.
