### ISSUE TITLE
Validate output changes?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#14]
(via a call with Sita today)

Sita said:

> Can we make the verbosity of the errors on submission less verbose? Or is there value in having all this detail printed out?

![Screenshot 2023-12-14 at 9 41 52 AM](https://github.com/FredHutch/shiny-cromwell/assets/577668/25e8234b-198d-4067-9bb3-9694aad36664)

A few options come to mind:

1. Make the output be html style. That is, we could output a view of the errors that is prettified in html, e.g., have different kinds of errors under different sections that could be toggled open/closed
2. Or even if just R text output, it seems like it would be easier to look at if we used https://cli.r-lib.org/ to differentiate different parts of the text of the error outputs, including icons, etc. 

cc @sitapriyamoorthi

**Comment by vortexing** [comment]
This is the raw response from womtool.  If you want to parse the json response so that it's easier to see for users, parsing a json isn't the worst.  But you'll find edge cases depending on the types of errors which means you run the risk of having new errors created in showing the validation responses depending on the type of validation failures.  

Is there a way to do a minimal clean up that would work for arbitrary validation responses?  @sckott ?

**Comment by sckott** [comment]
@vortexing 

> Is there a way to do a minimal clean up that would work for arbitrary validation responses?

i'll check

@sitapriyamoorthi can you please share with me some files (Wdl, json, whatever) that create the errors above or similar?

**Comment by tefirman** [comment]
My gut says that this isn't worth the effort during v1.X. While troubleshooting a workflow, I feel like there's value in being as verbose as possible, so the only thing left is to beautify it into a table or something. Going to close this as "not planned", but definitely worth revisiting in v2.0.
