### ISSUE TITLE
Tracking page: make status count buttons clickable to filter results?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#140]
via @codebeaker study

She asked if we could make the status buttons with counts of each category at the top clickable to filter by that status. There is already a filter on the left hand sidebar to filter by 1 or more status categories. 

We could make the buttons clickable, BUT I don't see an easy way to provide AND functionality to the filtering. That is if a user wants to filter by **Succeeded** and **Failed** they can do that in the sidebar filter, but I can't imagine that working with button clicks 

Thoughts anyone?

**Comment by tefirman** [comment]
Clickability sounds cool, probably not super high priority, but if it's easy, let's do it! I wouldn't worry about AND functionality with those buttons, maybe just make it so that when you click one of them, it defaults to ONLY that one? And they can always get AND functionality from the side bar..

Setting as low priority and v1.3 unless people disagree.

**Comment by sckott** [comment]
Sorry, should have updated this issue. We have now changed the status counts to not be buttons so users should think they can click on them. So I think we can close this now if ok with you

<img width="803" alt="Screenshot 2024-10-10 at 12 40 11 PM" src="https://github.com/user-attachments/assets/87eedb15-be16-47c3-8c36-d2bae2afed42">

**Comment by tefirman** [comment]
Gotcha, that's perfect. Closing now!
