### ISSUE TITLE
Workflow details page updates

### ISSUE THREAD

**Issue by codebeaker** [FredHutch/shiny-cromwell#160]
1) move 'troubleshoot' to a tab here
2) have a loading indicator for when content is loading
3) have a sentence for when there is truly no content, e.g. for workflow options if there is no content there can be a sentence saying what would be there and that it's empty for this workflow
4) change title bar to 'WorkflowName (label1, label2)' instead of what it currently is which is something like 'workflow details for [workflowID]'
5) put workflow ID in top right of title bar where labels currently are
6) note in the new version there are no icons for the labels

[figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=493-424&t=0zdNr3XYbr0JbH2C-1)

**Comment by sckott** [comment]
- [ ] move 'troubleshoot' to a tab here
- [ ] have a loading indicator for when content is loading
- [ ] have a sentence for when there is truly no content, e.g. for workflow options if there is no content there can be a sentence saying what would be there and that it's empty for this workflow
- [ ] change title bar to 'WorkflowName (label1, label- [ ]' instead of what it currently is which is something like 'workflow details for [workflowID]'
- [ ] put workflow ID in top right of title bar where labels currently are
- [ ] note in the new version there are no icons for the labels

**Comment by sckott** [comment]
@codebeaker what does this mean?

> note in the new version there are no icons for the labels
