### ISSUE TITLE
For FH users, allow for PROOF flow and non PROOF flow?

### ISSUE THREAD

**Issue by sckott** [FredHutch/shiny-cromwell#22]
@vortexing @sitapriyamoorthi  For the version of this app that runs for FH users specifically, do you think we should allow for a non PROOF flow where users make their own Cromwell server and put in a URL and the PROOF flow? Or just the PROOF flow? 

The answer to this impacts the app - only supporting one makes the code simpler. But supporting both gives it more flexibility but code is harder to maintain. 

The most important question is what do think users want OR maybe what do we want users to do? 

To accomplish #17 we for sure need to support a non PROOF flow, but that's of course not alongside a PROOF flow for non FH users.

**Comment by sitapriyamoorthi** [comment]
Here are my two cents(and please feel free to correct any misconceptions I might have about the Cromwell functioning). 
> Do you think we should allow for a non-PROOF flow where users make their own Cromwell server

Here are a few use-cases that I think users could need this feature:
* Users might have jobs that could support a specific Cromwell version that is different from our Cromwell version.
* They might have some integrations with Cromwell, for eg: a cloud provider ?? which we do not support.

However, the larger question, is that do we want to support non-PROOF flow in our initial MVP.
@sckott : Do you think we can build this in such a way, that we can add non-PROOF flow support in future releases

Additionally we must think how must we prep PROOF now so that if we do decide in the future to support non-PROOF flow it does not impact traditional PROOF users.

**Comment by vortexing** [comment]
Yes, we want the shiny app to interact with proof (the fred hutch implementation of Cromwell), but also anyone else shoudl be able to use the app to connect to a different cromwell deployment too.  

Any cloud related integrations that are Cromwell specific have nothing to do with the app really.  

If we can have a login tab that people could customize to their use case but the rest of the app is general, that would be great.

**Comment by sckott** [comment]
Thanks both for your feedback. 

Got it on the importance of having both in the same app in the same user session. 

For FH it makes sense to have both in the app, and then in instructions for others to use it we could strive to make it easy to hide/remove the login flow if they just need the I-already-have-a-cromwell-server flow
