### ISSUE TITLE
Proof server - readiness test

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#86]
It'd be great if the proof server tab would also do a test to see if the server is ready.  Yes, it says it's UP but if it's not yet ready to respond to users hitting the API then it's confusing for users.

**Comment by sckott** [comment]
We do do this in a sense. See https://github.com/FredHutch/shiny-cromwell/blob/d3588110401e72a9add0cd5942d991096eb012a7/app/server.R#L231 where we disable the start button that page if the metadata from the proof API says the server is running (i.e., `canJobStart` is FALSE). 

Are you wanting something in addition that pings the actual cromwell server rather than using metadata from the proof API?

**Comment by tefirman** [comment]
Feels like we can close this one based on Scott's response, plus the "Job status: RUNNING" metadata at the top of the PROOF server tab. Probably more important to prioritize #113
