### ISSUE TITLE
'submit jobs' tab - add visual clarity for output of validate/troubleshoot 

### ISSUE THREAD

**Issue by jayoung** [FredHutch/shiny-cromwell#9]
hi there,

suggestion:  in the 'submit jobs' tab, to my beginner's eye, it is easy for things to get a bit visually cluttered, e.g. I first did a 'validate workflow' followed by 'troubleshoot a workflow'.  Both of them have both long and confusing outputs and it's hard to see which is which when I scroll up and down too quickly.

Easy fix:  make the background boxes for the two types of output (validate versus troubleshoot) a different color so that we don't scroll from one to the other without noticing.

and/or, add a 'clear output' button for each section

(my temptation when I see all that long output is to click the 'reload' button of my browser, and that disconnects me from my server, which is more annoying than the long output was in the first place)

seems like a tiny detail but I'd find it very helpful 

thanks!

Janet

**Comment by vortexing** [comment]
#18 is a similar feeling I think.  Let's fix that though!!!

**Comment by sckott** [comment]
@vortexing  I'm guessing this was opened when the validate and troubleshoot bits were on the same page? Since they're on totally separate pages now this can probably be closed. 

There is still the issue of the outputs of validate and troubleshoot being hard to grok cause it's just a nested R list, but we can open a new issue for that
